class BaseApplicationException(Exception): ...


class DataCacheEmptyCacheError(BaseApplicationException): ...


class DataCacheUpdateError(BaseApplicationException): ...


class FileHandlerReadFileError(BaseApplicationException): ...


class FileHandlerWriteFileError(BaseApplicationException): ...


class FileHandlerOperationError(BaseApplicationException): ...
